//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Winscore.rc
//
#define IDC_LANDING                     2
#define ID_DELETE                       3
#define IDC_RESET                       3
#define IDRESET                         3
#define IDC_COPY                        3
#define IDSTOP                          3
#define IDC_LANDING2                    3
#define IDC_PEV                         3
#define ID_PLAN_TASKS                   4
#define IDCLEAR                         6
#define IDD_ABOUTBOX                    100
#define ID_DIALOG_BAR                   103
#define IDB_SPLASHORIG                  104
#define IDC_SECONDSTATUS                104
#define ID_INDICATOR_DATE               105
#define ID_INDICATOR_TIME               106
#define IDC_PROGRESSBAR                 106
#define IDD_EDITPP1                     107
#define IDS_CONTROL_BAR                 107
#define IDC_ANIMATION                   109
#define IDR_DOWNLOAD_ANIMATION          126
#define IDR_MAINFRAME                   128
#define IDR_WINSCOTYPE                  129
#define IDR_NOCONTEST                   129
#define IDD_TURNPOINT                   130
#define IDR_MAINFRAMEXML                130
#define IDD_CONTEST_INFO                131
#define IDD_CONTESTANT                  132
#define IDD_CONTESTANT_ADDRESS          135
#define IDB_BITMAP1                     140
#define IDD_CONTROL_BAR                 141
#define IDD_TIMES                       146
#define IDD_TASK                        149
#define IDD_LANDING                     151
#define IDD_FLIGHT_DATA                 154
#define IDD_WINDS                       155
#define IDD_LANDOUT_COORDINATES         156
#define IDB_SPLASH                      161
#define IDD_CALCULATE                   164
#define IDD_PENALITY                    165
#define IDD_EXPORT_SCORESHEET           167
#define IDD_GRID_POSITIONS              170
#define IDD_INVALID_LEGS                171
#define IDR_BIGICON                     172
#define IDD_EXPORT_STATUS               173
#define IDD_PREVIEW                     174
#define IDD_DESCRIPTION                 175
#define IDD_FDR_SETTINGS                176
#define IDD_TASK_PLANNER                177
#define IDD_IMPORT_EVENTS               178
#define IDD_TASKINFO                    182
#define IDD_IMPORT_FLIGHTS              187
#define IDD_FDR_UPLOAD_SETTINGS         188
#define IDD_COPYSCORESHEET              190
#define IDR_FLIGHTMENU                  191
#define IDD_SHOWWARNINGS                192
#define IDD_EDIT_FLIGHT                 193
#define IDD_FLIGHT_ANALYSIS             198
#define IDD_DISPLAY_FLIGHT              200
#define IDB_PLAYBITMAP                  202
#define IDB_STOPBITMAP                  203
#define IDD_EXPORT_FLIGHT_FILE          204
#define IDD_EXCLUDE_CONTESTANTS         205
#define IDD_GATE                        206
#define IDD_TURNPOINT_PICKER            209
#define IDD_ASSIGNEDPOINTSPROPPAGE      210
#define IDD_CLASSPROPPAGE               211
#define IDD_POSTPOINTSPROPPAGE          212
#define IDC_CURSOR1                     216
#define IDD_PRINT_GRID_POSITIONS        217
#define IDD_FDR_SETTINGS_PROPPAGE       219
#define IDD_FDR_ANALYSIS_PROPPAGE       221
#define IDD_REGISTER                    222
#define IDB_SMALLSPLASH                 223
#define IDD_REALTIME                    224
#define IDD_REALTIME_PROP_PAGE          226
#define IDD_REALTIME_INFO               227
#define IDD_CONTEST_SETTINGS            228
#define IDD_PROTOTYPE_TASK              230
#define IDD_TASK_TURNPOINTS             231
#define IDD_TASK_TIMES                  232
#define IDD_LANDING_LOCATION            233
#define IDD_CHANGE_TURNPOINT_LOCATION   234
#define IDR_SCORELIST                   235
#define IDD_TASKDISPLAY                 236
#define IDD_HANDICAP                    238
#define IDD_DONT_SHOW                   239
#define IDD_EDITPP5                     240
#define IDD_EDITPP2                     241
#define IDD_EDITPP3                     242
#define IDD_FLIGHT_SEARCH               245
#define IDD_DETAILED_SCORES             246
#define IDD_SERVER_SCORES               247
#define IDD_SCORE_REPORT                248
#define IDR_COPYMENU                    250
#define IDD_ALTERNATE_START             251
#define IDD_LOG_TRANSFER_SETINGS        252
#define IDD_CONTESTANTS_FROM_SSA        253
#define IDD_AUTOEXPORT_DIALOG           254
#define IDB_TREE_BMPS                   255
#define IDD_SAA_PICKER                  256
#define IDR_CONTESTANT_TREE_MENU        257
#define IDR_SETUP_TREE_MENU             258
#define IDR_CONTEST_TREE_MENU           259
#define IDR_CONTROL_TREE_MENU           260
#define IDR_LOG_TREE_MENU               261
#define IDR_SCORE_TREE_MENU             262
#define IDD_SSA_LOGIN                   263
#define IDR_CONTESTANT1                 263
#define IDD_AUTOMATIC_SCORING           264
#define IDD_EMAIL_SETTINGS              265
#define IDD_SELECT_CLASS_DIALOG         266
#define IDD_NOLOGFOUNDSTATUS            268
#define IDR_COPY_ANALYSIS               269
#define IDR_PRECONTESTFLIGHTMENU        270
#define IDD_AUTOSAVE_OPTIONS            271
#define IDR_RECORDER_MENU               272
#define IDR_MENU1                       273
#define IDR_AVI1                        402
#define IDC_TURNPOINT_ID                1000
#define IDC_CONTEST_NAME                1000
#define IDC_HOURS                       1000
#define IDC_FILE_EDIT                   1000
#define IDC_STATUS                      1000
#define IDC_NAME                        1001
#define IDC_STANDARD_CHECK              1001
#define IDC_WIND_CHECK                  1001
#define IDC_LAT_DEG                     1002
#define IDC_15METER_CHECK               1002
#define IDC_MAXPOST_CHECK               1002
#define IDC_UPLOAD                      1002
#define IDC_CHECK3                      1003
#define IDC_SPORTS_CHECK                1003
#define IDC_FINISH_CHECK                1003
#define IDC_LEG_CHECK                   1003
#define IDC_ROOT_FAIRING_CHECK          1003
#define IDC_SEND_SCORES_CHECK           1003
#define IDC_LONG_DEG                    1004
#define IDC_CHECK4                      1004
#define IDC_OPEN_CHECK                  1004
#define IDC_DISTANCECHECK               1004
#define IDC_OUT_THE_TOP_CHECK           1004
#define IDC_SGS126_CHECK                1005
#define IDC_LAT_MIN                     1006
#define IDC_CONTEST_LOCATION            1006
#define IDC_MINUTES                     1006
#define IDC_POST_HOURS                  1006
#define IDC_SPEED                       1006
#define IDC_CODE                        1006
#define IDC_FDR_COMBO                   1006
#define IDC_MAX_POST_HOURS              1006
#define IDC_LAT_SEC                     1007
#define IDC_POST_MINUTES                1007
#define IDC_LONG_MIN                    1008
#define IDC_MAXPOST_HOURS               1008
#define IDC_MAXPOST_HOURS_TEXT          1008
#define IDC_MAX_POST_HOURS_TEXT         1008
#define IDC_LONG_SEC                    1009
#define IDC_NATIONAL_RADIO              1009
#define IDC_AM_RADIO                    1009
#define IDC_ATTURNPOINT_RADIO           1009
#define IDC_MAXPOST_MINUTES             1009
#define IDC_MAXPOST_MINUTES_TEXT        1009
#define IDC_MAX_POST_MINUTES_TEXT       1009
#define IDC_NORTH                       1010
#define IDC_NONSANCTIONED_RADIO         1010
#define IDC_PM_RADIO                    1010
#define IDC_ATLATLONG_RADIO             1010
#define IDC_EXEPATH                     1010
#define IDC_SOUTH                       1011
#define IDC_REGIONAL_RADIO              1011
#define IDC_FINISHED_RADIO              1011
#define IDC_EAST                        1012
#define IDC_DAILY_PENALITY              1012
#define IDC_UPLOADPATH                  1012
#define IDC_WEST                        1013
#define IDC_NUMBER_DAYS                 1013
#define IDC_LOGPATH                     1013
#define IDC_COMBO1                      1014
#define IDC_CONTROL_BAR_VIEW            1014
#define IDC_DATE_COMBO                  1014
#define IDC_NUMBER_DAYS2                1014
#define IDC_NUMBER_PRACTICE_DAYS        1014
#define IDC_STARTCOMBO                  1015
#define IDC_REALTIMEPATH                1015
#define IDC_SUAFILENAME                 1015
#define IDC_MODEL_COMBO                 1015
#define IDC_START_DAY                   1016
#define IDC_MANUFACTURER_COMBO          1016
#define IDC_SUAFILENAME2                1016
#define IDC_EDIT7                       1017
#define IDC_MAX_SPEED                   1017
#define IDAPPLY                         1018
#define IDC_CONTROL_BAR_DAY             1018
#define IDC_ATTEMPTING_COMBO            1018
#define IDC_CONTESTNO_COMBO             1018
#define IDC_TYPE_COMBO                  1018
#define IDC_DATE_COMBO2                 1018
#define IDDELETE                        1019
#define IDC_UNITS_STATUTE_MILES_RADIO   1019
#define IDC_LANDED_RADIO                1019
#define IDC_HHMMSS                      1020
#define IDC_UNITS_NAUTICAL_RADIO        1020
#define IDC_DAY_RADIO                   1020
#define IDD_PROGRESS                    1020
#define IDC_HHMMMM                      1021
#define IDC_UNITS_KILOMETERS_RADIO      1021
#define IDC_CUM_RADIO                   1021
#define IDD_CONTESTANT1                 1021
#define IDC_LAT_SEC_TEXT                1022
#define IDC_HHMMSS2                     1022
#define IDD_TASKLIBRARY                 1022
#define IDC_LONG_SEC_TEXT               1023
#define IDC_APPLY                       1023
#define IDC_HHMMMM2                     1023
#define IDC_DELETE                      1024
#define IDC_CONTESTANT_PERSONAL         1027
#define IDC_IMPORT_CONTESTANT           1028
#define IDC_FDR_BUTTON                  1029
#define IDC_CONTEST_NO                  1030
#define IDC_FIRST_NAME                  1031
#define IDC_CLASS_COMBO                 1032
#define IDC_LAST_NAME                   1033
#define IDC_MIDDLE_NAME                 1034
#define IDC_GLIDER_MAKE                 1035
#define IDC_GLIDER_HANDICAP             1036
#define IDC_CITIZENSHIP_COMBO           1037
#define IDC_RECORDER_CHECK              1038
#define IDC_SSA_NUMBER                  1039
#define IDC_HANDICAP_TEXT               1040
#define IDC_CITY                        1044
#define IDC_ADDRESS1                    1046
#define IDC_ADDRESS2                    1047
#define IDC_STATE                       1048
#define IDC_ZIP1                        1049
#define IDC_ZIP2                        1050
#define IDC_COMBO2                      1052
#define IDC_CONTROL_BAR_CLASS           1052
#define IDC_EVENT_COMBO                 1052
#define IDC_POINTCOMBO                  1052
#define IDC_STATUSCOMBO                 1052
#define IDC_SSA                         1052
#define IDC_CONTROL_BOX                 1053
#define IDC_LIST_CONTROL                1056
#define IDC_START_MONTH                 1058
#define IDC_CONTROL_BAR_CLASS_TEXT      1063
#define IDC_CONTROL_BAR_DAY_TEXT        1064
#define IDC_START_YEAR_SPIN             1065
#define IDC_START_YEAR                  1066
#define IDC_NUM_CONTEST_DAYS_TEXT       1068
#define ID_APPLY                        1069
#define IDC_SECONDS                     1070
#define IDC_EXPLAIN                     1070
#define IDC_TIME_LIST_BOX               1072
#define IDC_STATUS_LIST                 1072
#define IDC_PENALITY_LIST               1072
#define IDC_LIST                        1072
#define IDC_REMOVE_BUTTON               1077
#define IDC_FIRSTTURN_COMBO             1079
#define IDC_LASTTURNTYPE_COMBO          1080
#define IDC_LATLONG_BUTTON              1080
#define IDC_LASTTURN_COMBO              1081
#define IDC_EDIT8                       1085
#define IDC_ASSIGNED_RADIO              1090
#define IDC_POST_RADIO                  1091
#define IDC_OPEN_HOURS                  1092
#define IDC_ASSIGNED_RADIO2             1092
#define IDC_OPEN_MINUTES                1093
#define IDC_POST_RADIO2                 1093
#define IDC_FTI_HOURS                   1094
#define IDC_FTI_MINUTES                 1095
#define IDC_TURNPOINT_COMBO             1096
#define IDC_ADD_BUTTON                  1097
#define IDC_LANDOUT_TURNPOINT_COMBO2    1098
#define IDC_FTI_HOURS2                  1098
#define IDC_FTI_MINUTES2                1099
#define IDC_MAX_POST_MINUTES            1099
#define IDC_FIRSTTURNTYPE_COMBO         1100
#define IDC_WIND_BUTTON                 1101
#define IDC_ASSIGNED_TEXT               1102
#define IDC_POST_TEXT                   1103
#define IDC_FIRSTTURN_TEXT              1104
#define IDC_LASTTURN_TEXT               1105
#define IDC_POSTMIN_TEXT                1106
#define IDC_POSTHOURS_TEXT              1107
#define IDC_MIN_POST_HOURS_TEXT         1107
#define IDC_POSTTIME_TEXT               1108
#define IDC_GATEOPEN_TEXT               1109
#define IDC_FTI_TEXT                    1110
#define IDC_OPENHOURS_TEXT              1111
#define IDC_GATEoPEN_MIN                1112
#define IDC_FTI_MINUTE_TEXT             1113
#define IDC_FTI_HOURS_TEXT              1114
#define IDC_INTERVAL_HOURS              1115
#define IDC_INTERVAL_MINUTES            1116
#define IDC_STI_TEXT                    1117
#define IDC_INTERVAL_HOURS_TEXT         1118
#define IDC_INTERVALMINUTE_TEXT         1119
#define IDC_CONTESTDAY_CHECK            1120
#define IDC_OFFICIAL_CHECK              1121
#define IDC_DIRECTION                   1122
#define IDC_INTERVAL_HOURS2             1122
#define IDC_MIN_POST_HOURS              1122
#define IDC_TURNPOINT_LIST              1123
#define IDC_MAXPOSTHOURS_TEXT           1124
#define IDC_INTERVAL_MINUTES2           1124
#define IDC_MIN_POST_MINUTES            1124
#define IDC_LOCATION_TEXT               1125
#define IDC_MAXPOSTMIN_TEXT             1125
#define IDC_DISTANCE_TEXT               1126
#define IDC_FTI_MINUTE_TEXT2            1126
#define IDC_STARTFINISH_TEXT            1128
#define IDC_POST_MINUTE_TEXT            1128
#define IDC_MIN_POST_MINUTES_TEXT       1128
#define IDC_ACHEIVED_TEXT               1129
#define IDC_FORMAT_TEXT                 1130
#define IDC_LAT_TEXT                    1131
#define IDC_LONG_TEXT                   1132
#define IDC_LONGDEG_TEXT                1133
#define IDC_LONGMIN_TEXT                1134
#define IDC_LATSEC_TEXT                 1135
#define IDC_LONGSEC_TEXT                1136
#define IDC_LATMIN_TEXT                 1137
#define IDC_LATDEG_TEXT                 1138
#define IDC_CONTESTANT_COMBO            1139
#define IDC_NOTASK_TEXT                 1140
#define IDC_LATLONG_TEXT                1141
#define IDC_ATTEMPTING_TEXT             1142
#define IDC_CLASS_TAB                   1152
#define IDC_DATE                        1155
#define IDC_CONTEST_COMBO               1156
#define IDC_PERCENT_OR_POINTS           1161
#define IDC_BROWSE_BUTTON               1162
#define IDC_STI_RULES_CHECK             1166
#define IDC_STATUS_COMBO                1167
#define IDC_STATUS_TEXT                 1170
#define IDC_FROM_COMBO                  1173
#define IDC_TO_COMBO                    1174
#define IDC_SPEED_TEXT                  1175
#define IDC_VERSION_TEXT                1176
#define IDC_HELP_BUTTON                 1180
#define IDC_STATIC_TEXT                 1183
#define IDC_STATIC_YEAR                 1184
#define IDC_WORLD_CHECK                 1185
#define IDC_18M_CHECK                   1186
#define IDC_18METER_CHECK               1188
#define IDC_FORMAT_COMBO                1189
#define IDC_IMPORT                      1190
#define IDC_AIRFIELD                    1192
#define IDC_HOME_CHECK                  1193
#define IDC_START_CHECK                 1194
#define IDC_AIRFIELD_CHECK              1195
#define IDC_TURNPOINT_CHECK             1196
#define IDC_EDIT1                       1197
#define IDC_DESCRIPTION                 1198
#define IDC_MDP_B_EDIT                  1198
#define IDC_START_GRID_NUMBER           1198
#define IDC_OUTER_RADIUS                1198
#define IDC_EDIT_WINGLET                1198
#define IDC_USERNAME_EDIT               1198
#define IDC_EDIT_AUTOSAVE               1198
#define IDC_EDIT_DM                     1198
#define IDC_FDRCHECK                    1199
#define IDC_SPACES                      1199
#define IDC_WEIGHT_EDIT                 1199
#define IDC_PASSWORD_EDIT               1199
#define IDC_FDRBUTTON                   1200
#define IDC_MAILBOX_EDIT                1200
#define IDC_FINISH                      1201
#define IDC_FDRFINISH                   1201
#define IDC_START                       1202
#define IDC_COMMENT                     1203
#define IDC_START_HEIGHT                1203
#define IDC_INFO_BAR                    1204
#define IDC_FINISH_BASE                 1204
#define IDC_CHECK1                      1205
#define IDC_SUMMARYCHECK                1205
#define IDC_BASE_EDIT                   1205
#define IDC_CHECK2                      1206
#define IDC_TABCHECK                    1206
#define IDC_GPSCHECK                    1206
#define IDC_WITHDREW_CHECK              1206
#define IDC_ROLLINGCHECK                1206
#define IDC_STARTCHECK                  1206
#define IDC_TURBULATION_CHECK           1206
#define IDC_ANALYZE_CHECK               1206
#define IDC_GATE_PERP_CHECK             1206
#define IDC_PERP_CHECK                  1206
#define IDC_BUTTON1                     1207
#define IDC_PLAN_TASK                   1207
#define IDC_LOCATION_BUTTON             1207
#define IDC_BROWSE_EXE                  1207
#define IDC_FIND_START                  1207
#define IDC_PLAYBUTTON                  1207
#define IDC_VIEW_BUTTON                 1207
#define IDC_TASK_PLANNER                1207
#define IDC_CLASSPROPERTIESBUTTON       1207
#define IDC_REGISTRATION_HELP           1207
#define ID_REGISTER_WINSCORE            1207
#define IDC_REFRESH                     1207
#define IDC_TURNPOINT_BUTTON            1207
#define IDC_LANDING_LOCATION            1207
#define IDC_HCLOOKUPBUTTON              1207
#define IDC_BUTTON2                     1208
#define IDC_BROWSE_UPLOAD               1208
#define IDC_PREV_TURNPOINT              1208
#define IDC_TASK_PLANNER2               1208
#define IDC_BROWSE_LOG_PATH             1209
#define IDC_NEXT_TURNPOINT              1209
#define IDC_STF_CHECK                   1209
#define IDC_LANDEDCHECK                 1209
#define IDC_FILENAME                    1210
#define IDC_FIND_FINISH                 1210
#define IDC_BROWSE_REALTIME_PATH        1210
#define IDC_BROWSE_SUAFILE              1210
#define IDC_BROWSE                      1211
#define IDC_BROWSE_SUAFILE2             1211
#define IDC_IMPORT_BUTTON               1212
#define IDC_STIFACTOR                   1213
#define IDC_STIFACTORTEXT               1214
#define IDC_MOD_RADIO                   1215
#define IDC_FINISHEDCHECK               1216
#define IDC_MOD_RADIO2                  1216
#define IDC_RADIO                       1217
#define IDC_MOD_RADIO3                  1217
#define IDC_RADIO2                      1218
#define IDC_RADIO3                      1219
#define IDC_RADIO4                      1220
#define IDC_RADIO_TP                    1221
#define IDC_SLIDER                      1241
#define IDC_TASKCONTROL                 1243
#define IDC_EDIT                        1251
#define IDC_ELEVATION                   1253
#define IDC_STATUSRADIO                 1253
#define IDC_RADIO5                      1254
#define IDC_LISTBOX                     1254
#define IDC_RADIO6                      1255
#define IDC_EDIT_TURNPOINTS             1255
#define IDC_FORMATRADIO                 1256
#define IDC_RADIO7                      1257
#define IDC_TEXTRADIO                   1258
#define IDC_RADIO_OTHER                 1258
#define IDC_RADIO_FURTHEST              1259
#define IDC_TP_SPIN                     1263
#define IDC_DATETIMEPICKER_ROLL         1264
#define IDC_DATETIMEPICKER_START        1265
#define IDC_DATETIMEPICKER_FINISH       1266
#define IDC_DATETIMEPICKER_LANDING      1267
#define IDC_FINISH_TEXT                 1268
#define IDC_LANDING_GROUP_TEXT          1269
#define IDC_LIST2                       1271
#define IDC_HEADINGTEXT                 1272
#define IDC_HEADING_EDIT                1273
#define IDC_STARTHEADINGTEXT            1274
#define IDC_START_HEADING_EDIT          1275
#define IDC_START_RADIUS_TEXT           1276
#define IDC_FINISH_RADIUS_TEXT          1277
#define IDC_WSVIEWCTRL                  1278
#define ID_FLIGHT_DISPLAY               1281
#define IDC_LATLONGEDIT                 1282
#define IDC_TIME_INTERVAL_EDIT          1284
#define IDC_PROGRESS                    1286
#define IDC_STATUS_EDIT                 1287
#define IDC_CLASS_LIST                  1288
#define IDC_FILENAME_EDIT               1289
#define IDC_LIST1                       1290
#define IDC_RADIO_UPLOAD                1291
#define IDC_IMPORT_FILES                1292
#define IDC_RADIO_IMPORT                1293
#define IDC_MANUFACTURER_TEXT           1294
#define IDC_TYPECOMBO                   1295
#define IDC_RADIUS_EDIT                 1296
#define IDC_HEIGHT_EDIT                 1297
#define IDC_BASE_TEXT                   1298
#define IDC_HEIGHT_TEXT                 1299
#define IDC_RADIUS_TEXT                 1300
#define IDC_HEADING_TEXT                1301
#define IDC_TYPE_TEXT                   1302
#define IDC_SELECTPOINTSBUTTON          1304
#define IDC_TASKOPEN_DATETIMEPICKER     1305
#define IDC_START_GATE_BUTTON           1306
#define IDC_FINISH_GATE_BUTTON          1307
#define IDC_TURNPOINT_TEXT              1308
#define IDC_START_GATE_BUTTON2          1308
#define IDC_MINIMUMTIME_PICKER          1308
#define IDC_TURNPOINT_EDIT              1309
#define IDC_START_GATE_BUTTON3          1309
#define IDC_MAXIMUM_TIME_PICKER         1309
#define IDC_STI_TIME_PICKER             1310
#define IDC_RADII_EDIT                  1310
#define IDC_CHECKEDLIST                 1311
#define IDC_FDI_TIME_PICKER             1311
#define IDC_RADII_TEXT                  1311
#define IDC_SMTD_EDIT                   1312
#define IDC_SMTT_EDIT                   1313
#define IDC_NOFINISH_POINTS_EDIT        1314
#define IDC_MSP_B_EDIT                  1317
#define IDC_MSP_M_EDIT                  1318
#define IDC_MDP_M_EDIT                  1319
#define IDC_AIRFIELD_BONUS_EDIT         1320
#define IDC_114F_STATIC                 1321
#define IDC_114G_STATIC                 1322
#define IDC_115H_STATIC                 1323
#define IDC_115I_STATIC                 1324
#define IDC_SCR1_STATIC                 1325
#define IDC_SCR2_STATIC                 1326
#define IDC_STARTDATEPICKER             1328
#define IDC_CLASSLIST                   1329
#define IDC_NAME_EDIT                   1330
#define IDC_HANDICAPPING_CHECK          1331
#define IDC_SCR_CHECK                   1332
#define IDC_UNIT_TEXT                   1333
#define IDC_CODE_COMBO                  1334
#define IDC_GRID_NUMBER_TEXT            1339
#define IDC_NUM_ROWS_TEXT               1340
#define IDC_SPACES_TEXT                 1341
#define IDC_DAY_PLUS                    1346
#define IDC_DAY_MINUS                   1347
#define IDC_NUM_ROWS_SPIN               1348
#define IDC_NUM_ROWS_EDIT               1349
#define IDC_DAYS_TO_PRINT               1351
#define IDC_DAYS_TO_PRINT_SPIN          1352
#define IDC_LETTER_CHECK                1353
#define IDC_START_SPIN                  1354
#define IDC_SPACES_SPIN                 1355
#define IDC_INNER_RADIUS                1355
#define IDC_UNITS1                      1356
#define IDC_UNITS2                      1357
#define IDC_REGISTRATION_NUMBER         1359
#define IDC_PICTURE                     1360
#define ID_CONTINUE                     1361
#define ID_REGISTER                     1362
#define IDC_REG1                        1363
#define IDC_REG_NAME                    1364
#define IDC_WSVIEWCTRL1                 1364
#define IDC_REG_NUMBER                  1365
#define IDC_INFO                        1365
#define IDC_GUEST_CHECK                 1367
#define IDC_CONTEST_SETTINGS            1368
#define IDC_LOGRADIO                    1369
#define IDC_SYSTEMRADIO                 1370
#define IDC_USERRADIO                   1371
#define IDC_LOCAL_TIMEZONE_EDIT         1372
#define IDC_MOTORCHECK                  1373
#define IDC_TEXT1                       1376
#define IDC_TEXT2                       1377
#define IDC_TEXT3                       1378
#define IDC_TEXT4                       1379
#define IDC_STATUS_RADIO                1381
#define IDC_PRELIM_RADIO                1382
#define IDC_UNOFFICIAL_RADIO            1383
#define IDC_OFFICIAL_RADIO              1384
#define IDC_TASKTYPETEXT                1385
#define IDC_TIME_BUTTON                 1386
#define IDC_TYPE_RADIO                  1388
#define IDC_STI_GROUP_TEXT              1389
#define IDC_UNITSTEXT                   1390
#define IDC_TASK_STATUS_TEXT            1391
#define IDC_AREA_RADIO                  1392
#define IDC_FAI_RACE_RADIO              1393
#define IDC_ZOOMINBUTTON                1394
#define IDC_FAI_ASSIGNED_AREA           1394
#define IDC_ZOOMOUTBUTTON               1395
#define IDC_GATE_GROUP_COMBO            1395
#define IDC_ZOOMTASKBUTTON              1396
#define IDC_2ND_GATE_CHECK              1396
#define IDC_DISPLAYOPTIONSBUTTON        1397
#define IDC_START_GATE_BUTTON_B         1397
#define IDC_AUTOSCALE                   1398
#define IDC_TWO_GATE_CHECK              1398
#define IDC_GATE_GROUP_TEXT             1399
#define IDC_STARTGATE                   1400
#define IDC_START_GATE_CHECK            1402
#define IDC_STARTGATEGROUP              1403
#define IDC_LANDINGLOCATIONGROUP        1404
#define IDC_VIEWLOG                     1405
#define IDC_PROGRESSRADIO               1407
#define IDC_SPIN1                       1409
#define IDC_CONTROLPOINTDISTANCETEXT    1411
#define IDC_DISTANCEFLOWNTEXT           1412
#define IDC_LOGPOINTEDIT                1413
#define IDC_CHANGETURNPOINTBUTTON       1414
#define IDC_FLIGHTLOGGROUP              1415
#define IDC_WSBAROCTRL                  1416
#define IDC_SUACHECK                    1417
#define IDC_SUAFILETEXT                 1418
#define IDC_TEXT                        1419
#define IDC_SUACHECK2                   1419
#define IDC_HANDICAP_EDIT               1420
#define IDC_SUAFILETEXT2                1420
#define IDC_DLG_ICON                    1421
#define IDC_NOTES_TEXT                  1422
#define IDC_SPAN_EDIT                   1423
#define IDC_SPAN_TEXT                   1424
#define IDC_WEIGHT_TEXT                 1425
#define IDC_COMPLETED_TASK              1426
#define IDC_START_COMBO                 1427
#define IDC_UPDATE_DISTANCE             1428
#define IDC_ADD                         1430
#define IDC_REMOVE                      1431
#define IDC_MOVEUP                      1432
#define IDC_ROLLCHECK                   1433
#define IDC_ADD2                        1433
#define IDC_FINISHCHECK                 1434
#define IDC_EDITDISTANCE                1435
#define IDC_LANDOUTGROUP                1436
#define IDC_TURNPOINTCHECK              1437
#define IDC_SCOREDLPCHECK               1438
#define IDC_LANDOUTEDIT                 1439
#define IDC_CHANGLANDOUTBUTTON          1440
#define IDC_WORSTCHECK                  1441
#define IDC_LISTCTRL                    1442
#define IDC_CHANGEFIXES                 1443
#define IDC_TURNPOINTTEXT               1444
#define IDC_ZOOMOUT                     1445
#define IDC_ZOOMIN                      1446
#define IDC_CHANGEPLUSBUTTON            1447
#define IDC_CHANGEMINUSBUTTON           1448
#define IDC_TEST                        1451
#define ID_SEND                         1452
#define IDC_COMMENT_BUTTON              1453
#define IDC_SETTINGS                    1454
#define IDC_EDIT_STATUS                 1455
#define IDC_EXCLUDE                     1456
#define IDC_TEST_CHECK                  1459
#define IDC_RADIO1                      1460
#define IDC_ALT_START                   1461
#define IDC_RADIO_REMIND                1461
#define IDC_TOP                         1462
#define IDC_RADIO_AUTOSAVE              1462
#define IDC_SPIN2                       1463
#define IDC_TIME                        1464
#define IDC_MINTIMETEXT                 1465
#define IDC_CONDENSE_CHECK              1466
#define IDC_TRANSFER_TEXT               1467
#define IDC_TRANSFER_TEXT2              1468
#define IDC_LOOKUP_BUTTON               1470
#define IDC_SAFETY_CHECK                1471
#define IDC_WINGLET_CHECK               1472
#define IDC_PATH                        1473
#define IDC_SSA_BUTTON                  1474
#define IDC_OK                          1475
#define IDC_EDIT_PASSWORD               1476
#define IDC_EDIT_USERNAME               1477
#define IDC_REMEMBER_CHECK              1478
#define IDC_EMAIL_CHECK                 1479
#define IDC_NEXT_EVENT_STATIC           1480
#define IDC_NUM_SECONDS_EDIT            1481
#define IDSTART                         1482
#define IDC_EVENT_LIST                  1483
#define IDC_EMAIL_SETTINGS_BUTTON       1484
#define IDC_TRANSFER_SETTINGS_BUTTON    1485
#define IDC_SERVER_EDIT                 1486
#define IDC_SSL_CHECK                   1487
#define IDC_PORT_EDIT                   1488
#define IDC_CLOSE                       1490
#define IDC_RECHECK_LATEST              1491
#define IDC_APPLY_PENALTY               1492
#define IDC_SECURITY_PASSED             1493
#define IDC_CLEAR                       1494
#define IDC_MEDIA_CHECK                 1495
#define IDC_EXPORT                      1496
#define IDC_EXPORT2                     1497
#define IDC_UPDATE_FDR_ID               1497
#define IDC_SELECT                      1498
#define IDC_CANCEL                      1499
#define IDC_CHANGE_FOLDER               1500
#define IDC_VIEWTASK                    1501
#define IDC_TASK_MGMT_GROUP             1502
#define IDC_AUTOSAVE_CHECK              1504
#define IDC_STATIC_INFO                 1507
#define IDC_PROGRESS1                   1508
#define IDC_WGS84_RADIO                 1509
#define IDC_FAI_RADIO                   1510
#define IDC_RADIO_NONE                  1511
#define IDC_EDIT_REMIND                 1512
#define IDC_EDIT_D1                     1514
#define IDC_UNITS_DM                    1515
#define IDC_UNITS_D1                    1516
#define IDC_MAX_GROUND_SPEED            1517
#define IDC_GROUND_SPEED_UNITS          1518
#define IDC_MAX_GROUND_SPEED_TEXT       1519
#define IDC_MAX_START_ALTITUDE_TEXT     1520
#define IDC_MAX_ALTITUDE                1521
#define IDC_PRESTART_ALTITUDE           1522
#define IDC_PRESTART_ALTITUDE_UNITS     1523
#define IDC_MSA_UNITS                   1524
#define IDC_PEV_STATIC                  1525
#define IDC_ENABLE_PEV                  1526
#define IDC_STATIC_WAIT_TIME            1527
#define IDC_STATIC_PEV_START            1528
#define IDC_WAIT_TIME_EDIT              1529
#define IDC_PEV_START_WINDOW_EDIT       1530
#define IDC_FDR_ID                      1531
#define IDB_SMALLICONS                  26018
#define IDB_LARGEICONS                  26019
#define ID_CONTEST_INFO_TURNPOINT       32771
#define ID_CONTEST_INFO_INVALID_TPT     32772
#define ID_VIEW_TURNPOINT_GRID          32773
#define ID_CONTESTINFO_CONTESTANTS      32774
#define ID_CONTEST_INFO_CONTESTANTS     32775
#define ID_CONTESTINFO_TAKEOFFGRID      32776
#define ID_CONTEST_INFO_TAKEOFF_GRID    32777
#define ID_CONTEST_INFO_SETUP           32779
#define ID_DAILYINFO_TASK               32785
#define ID_DAILYINFO_TIMES              32786
#define ID_DAILYINFO_LANDINGCARDS       32787
#define ID_DAILYINFO_UPLOAD             32788
#define ID_DAILYINFO_CALCULATESCORES    32789
#define ID_BUTTON32802                  32802
#define ID_BUTTON32804                  32804
#define ID_DAILY_FLIGHTANALYSIS         32805
#define ID_DAILY_PENALITIES             32811
#define ID_ADJUST_SCORES                32812
#define ID_DAILY_PENALTIES              32813
#define ID_FILE_EXPORT_SCORESHEET       32816
#define ID_PREVIEW                      32817
#define ID_FILE_IMPORTFDRFILE           32819
#define ID_FILE_IMPORT_EVENTS           32821
#define ID_FILE_EXPORT_CONTESTANTS      32823
#define ID_DAILY_TASKPLANNER            32824
#define ID_FILE_IMPORT_FLIGHTS          32827
#define ID_FLIGHTLOGS_ANALYZEALL        32830
#define ID_FLIGHTLOGS_ANALYZEFLIGHT     32831
#define ID_FLIGHTLOGS_VIEWIGCFILE       32832
#define ID_FLIGHTLOGS_DELETE            32833
#define ID_FLIGHTLOGS_SETTINGS          32835
#define ID_FLIGHTLOGS_EDITFLIGHTRESLTS  32836
#define ID_FLIGHTLOGS_VIEWWARNINGS      32837
#define ID_FLIGHTLOGS_ANALYZENEW        32838
#define ID_FLIGHTLOGS_VIEWANALYSIS      32839
#define ID_FLIGHTLOGS_REFRESH           32840
#define ID_FLIGHTLOGS_DISPLAY           32841
#define ID_FILE_EXPORT_WINSCOREFLIGHTFILE 32843
#define ID_HELP_REGISTER                32844
#define ID_VIEW_REALTIMEFLIGHTDISPLAY   32845
#define ID_FLIGHTLOGS_VIEW              32848
#define ID_ANALYZE_INFO                 32849
#define ID_VIEW_GOTO_BACK               32850
#define ID_VIEW_GOTO_FORWARD            32851
#define ID_ANALYZE_SECURITY_MARKASPASSED 32855
#define ID_ANALYZE_SECURITY_MARKASFAILED 32856
#define ID_ANALYZE_SECURITY_CHECKCAIFILE 32857
#define ID_ANALYZE_DETAILEDINFO         32858
#define ID_FILE_EXPORT_CP_XML           32859
#define ID_FILE_EXPORT_CONTESTANTSINXMLFORMAT 32860
#define ID_FILE_IMPORT_CONTROLPOINTSINXMLFORMAT 32861
#define ID_FILE_IMPORT_XML_CONTESTANTS  32862
#define ID_SCORESHEET_SERVER            32863
#define ID_FILE_EXPORT_XML_ENTIRECONTESTFILE 32865
#define ID_FILE_IMPORT_XML_ENTIRECONTEST 32866
#define ID_HELP_WINSCOREMANUAL          32867
#define ID_IMPORT_FLASHCARD             32869
#define ID_SSA_SERVER                   32871
#define ID_FILE_IMPORT_CONTROLPOINTSINCAIDATFORMAT 32873
#define ID_FILE_EXPORT_AUTOEXPORTSCORESHEETTOXML 32874
#define ID_FLIGHTLOGS_CHECKSECURITY     32875
#define ID_VIEW_CONTROLBAR              32876
#define ID_VIEW_DLGBAR                  32877
#define ID_MANAGECONTESTANTS_MANAGECONTESTANTS 32878
#define ID_SCORES_CALCULATIONINFORMATION 32879
#define ID__IMPORTFROMSSA               32880
#define ID_EDIT1CONTESTANT              32881
#define ID_DELETE_CONTESTANT            32882
#define ID_CONTESTANT_EDIT1             32883
#define ID__ADDCONTESTANT               32884
#define ID_EXPORT_CONTESTANTS           32885
#define ID_IMPORT_CONTESTANTS           32886
#define ID_IMPORT_HANDICAPLISTFROMSSA   32887
#define ID_EXPORT_HANDICAPSUMMARYTOHTML 32888
#define ID_DAILY_AUTOSCORING            32889
#define ID_BUTTON32893                  32893
#define ID_FLIGHTLOGS_RECHECKLATESTSTART 32895
#define ID_ANALYZE_EXPORTTOTASKLIBRARY  32896
#define ID_EXPORT_TO_TASK_LIBRARY       32897
#define ID_EXPORT_ALLTASKSTOXMLFILE     32898
#define ID_ANALYZE_CHANGECLASS          32899
#define ID_CHANGECLASS                  32900
#define ID_ANALYZE_NOLOGSTATUS          32901
#define ID_NOLOGSTATUS_DIDNOTLAUNCH     32902
#define ID_NOLOGSTATUS_LANDOUTREPORTED  32903
#define ID_NOLOGSTATUS_NOLOGFOUND       32904
#define ID_NOLOGSTATUS_CUSTOM           32905
#define ID_REFRESH_ICON                 32906
#define ID_FILE_CHECKFORNEWVERSIONATSTARTUP 32907
#define ID_Menu                         32909
#define ID_NOLOGSTATUS_CHECKEDANDOK     32910
#define ID_LOGSTATUS_CHECKEDANDOK       32911
#define ID_EXPORT_TASK_TO_CUP           32912
#define ID_ANALYZE_SETCONTESTANTFDRID   32912
#define ID_SETCONTESTANTFDRID           32913
#define ID_SET_FDR_ID                   32914
#define ID_RECORDER_DELETE              32915
#define ID_RECORDER_DELETE32916         32916
#define NO_ROLL_TIME_DNC                61250
#define NO_FINISH_TIME                  61251
#define FINISHED_BUT_LANDOUT            61252
#define ROLL_LATER_USING_ROLL           61253
#define NO_START_AFTER_TASK_USING_ROLL  61254
#define NO_CODE_OR_REASON               61255
#define ZERO_PENALITY_POINTS            61256
#define MIN_TIME_GT_MAX                 61257
#define OVERWRITE_TAKEOFF_GRID          61258
#define SAME_INVALID_LEGS               61259
#define LOST_LEGS                       61260
#define INVALID_LEG_USED                61261
#define IDS_ERR_MAX_TURNPOINTS          61450
#define IDS_ERR_NO_TURNPOINT_NAME       61451
#define IDS_ERR_DUPLICATE_TURNPOINT_NAME 61452
#define IDS_ERR_TURNPOINTS_CANCEL       61453
#define IDS_ERR_INVALID_CONTEST_NO      61454
#define IDS_ERR_INVALID_GLIDER          61455
#define IDS_ERR_INVALID_PILOT_NAME      61456
#define IDS_ERR_CONTESTANTS_CANCEL      61458
#define IDS_ERR_NO_CLASSES              61459
#define IDS_ERR_NO_CONTEST_NAME         61460
#define IDS_ERR_CONTESTANT_NOT_FOUND    61461
#define IDS_ERR_TIMES_CANCEL            61462
#define IDS_ERR_TASK_MAX_TURNPOINTS     61463
#define IDS_ERR_LNDCRD_MAX_TURNPOINTS   61464
#define IDS_ERR_LNDCARD_TASK_NOT_FOUND  61465
#define IDS_ERR_LNDCARD_NO_TPT          61466
#define IDS_ERR_TASK_NO_TURNPOINTS      61467
#define NO_LANDING_CARD_DNC             61468
#define NO_START_USING_ROLL             61469
#define IDC_CONTROL_BAR_VIEW_TEXT       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32917
#define _APS_NEXT_CONTROL_VALUE         1532
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
