#if !defined(AFX_WSBARO_H__5F07D6EA_FCBB_4CC2_A4D0_08A866752903__INCLUDED_)
#define AFX_WSBARO_H__5F07D6EA_FCBB_4CC2_A4D0_08A866752903__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWSBaro wrapper class

class CWSBaro : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWSBaro)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x49134336, 0x1ce2, 0x11d4, { 0xb1, 0xd2, 0x54, 0xf8, 0x5e, 0x0, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	short AddPilot(LPCTSTR strContestNo, LPCTSTR strLastName, LPCTSTR strFirstName, short sClass, long lColorREF);
	void SetCursorPos(long lCursorTime);
	void AddPoint(short sPilotIndes, long lTimeIndex, short sGPSAltitude, short sPressureAltitude);
	void SetTimeRange(long lStartTime, long lEndTime);
	void AddPoints(const VARIANT& vlTime, const VARIANT& vstrContestNo, const VARIANT& vsPressureAlt, const VARIANT& vsGPSAlt);
	void ResetAll();
	void AddPointByName(LPCTSTR strContestNo, long lTimeIndex, short sGPSAltitude, short sPressureAltitude);
	void OnControlKey(short nChar);
	void SetTaskOpenTime(long lTime);
	void RedrawBaro();
	void SetPilotVisibility(LPCTSTR strContestNo, BOOL bVisible);
	long GetCursorPos();
	BOOL IsCursorEnd();
	void CursorHome();
	void AddFullPoint(short sPilotIndex, long lTimeIndex, short sGPSAltitude, short sPressAltitude, float fLat, float fLong, float fSpeed, float fVSpeed, short sENL);
	void SetDisplayOption(long lOption, short sValue);
	short GetDisplayOption(long lOption);
	void SetTaskCloseTime(long lTime);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WSBARO_H__5F07D6EA_FCBB_4CC2_A4D0_08A866752903__INCLUDED_)
