/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for winscore.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define Getting_Around_in_Winscore 1
#define Start_a_new_Contest 2
#define Control_Point_Management 3
#define Contestant_Management 4
#define Task_Management 5
#define HID_PLAN_TASKS 6
#define How_To_Make_a_contest_day_official 7
#define How_To_Make_a_day_a_no_contest_day 8
#define How_to_send_scoresheets_to_the_SSA 9
#define Using_Help_command_Help_menu 10
#define About_command_Help_menu 11
#define No_Help_Available 12
#define Conditions_of_Use 13
#define Invalid_Task_Leg_Management 14
#define Takeoff_Grid_Positions 15
#define Control_Point_Distance_Grid 16
#define Manage_Times 17
#define Landing_Cards 18
#define Penalties_and_Score_Adjustments 19
#define Previewing_and_Printing 20
#define Viewing_Score_Information 21
#define Exporting_Scoresheets 22
#define Contacting_the_Author 23
#define Flight_Log_Management 24
#define Notes_about_automatic_flight_analysis 25
#define HID_FLIGHT_DISPLAY 26
#define Introduction_to_Flight_Log_Analysis 27
#define Copy_and_Paste_Winscore_Data 28
/#define Export_Winscore_Flight_File 29
#define About_Winscore_Flight_Files 30
#define HID_PLAN_TASKS 31
#define Printing_Takeoff_Grid_Positions 32
#define HID_FLIGHT_DISPLAY 33
#define Winscore_Flight_Files 34
#define How_to_export_a_Winscore_Flight_File 35
#define HID_REGISTER_WINSCORE 36
#define Order_Form 37
#define HID_REGISTER_WINSCORE 38
#define Real_Time_Flight_Viewing 39
#define Importing_Flight_Logs 40
#define Troubleshooting_Automatic_Flight_Analysis 41
#define IGC_File_Naming_Convention 42
